### ISSUE TITLE
Problem with exe

### ISSUE THREAD

**Issue by Luigius** [ladimolnar/BitcoinDatabaseGenerator#1]
Hi, I download the latest compiled version and installed on a WIN 2012 R2 server with SQL Server 2012 Ent 
When I try to run the software I get an error related to a missing file or assebly 'Microsoft.SqlServer.Smo, Version=12,0,0,0 .....

I installed also all the SQL sdk and Visual Studio 2012.

Could you please also list the requirement to compile the source code?
I got several errors on opening the projects from Stylecop not present to references to not installed frameworks.

Thanks

**Comment by ladimolnar** [comment]
Thank you Luigius!

I will need a couple of days to install a VM with a clean environment to be able to repro your case and another one with a clean development environment to repro the StyleCop references issues. 

Meanwhile if you can respond to this thread with two new entries showing the errors in the production and in the dev environment it would help me make sure that I cover all issues. 

Thanks.

**Comment by Luigius** [comment]
Hi,
If you liked can give you access via teamview to my vm with the installation.

Let me know
Thanks
Luigi

**Comment by Luigius** [comment]
This is the error from the exe.
Thanks
Luigi

![untitled](https://cloud.githubusercontent.com/assets/4317527/7715154/192f4cb0-fe3a-11e4-9bd6-bddc395e2751.png)

**Comment by Luigius** [comment]
Here the Compiler errors.

Thanks
Luigi

![untitled1](https://cloud.githubusercontent.com/assets/4317527/7715225/8540a96c-fe3a-11e4-9ca4-06c746c03576.png)

**Comment by ladimolnar** [comment]
Hello Luigi, 

Regarding Microsoft.SqlServer.Smo I made some changes (uncommitted yet) and I no longer have dependencies on the SMO dlls. As soon as I test them on my VM I will commit the changes and publish a new release. ETA 48 hrs. 

Regarding the build errors they show you need to install at least two dependencies: 
- Install StyleCop from http://stylecop.codeplex.com/. I will add a readme file and some documentation on the wiki about the prerequisites on a development machine. If you do this, please let me know what the outcome is - I'd be happy to have a confirmation that this is the only necessary step. 
- Some SQL Server dependencies but they will no longer be a requirement as soon as I check-in the new changes (ETA 48 hrs).

**Comment by Luigius** [comment]
Hi,
I just installed Stylecop and works fine but ht other 2 projects generate the fallowing error:
D:\BitcoinDatabaseGenerator-1.0\Sources\ZeroHelpers\ZeroHelpers.csproj : error  : The project file 'ZeroHelpers' cannot be opened.

The project is targeting frameworks that are either not installed or are included as part of future updates to Visual Studio. See http://go.microsoft.com/fwlink/?LinkID=287985 for more information.

D:\BitcoinDatabaseGenerator-1.0\Sources\ResharperAnnotations\ResharperAnnotations.csproj : error  : The project file 'ResharperAnnotations' cannot be opened.

The project is targeting frameworks that are either not installed or are included as part of future updates to Visual Studio. See http://go.microsoft.com/fwlink/?LinkID=287985 for more information.

Thanks for your support.
Luigi

**Comment by ladimolnar** [comment]
Hello Luigi,

Your build errors are most likely caused by the fact that you use Visual Studio 2012. As far as I know Ms. allows individual developers to download and use Visual Studio Community 2013 for free but please do your own research especially if your use is inside an organization. See https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx

I created the tool using Visual Studio Professional 2013. The version I have is Version 12.0.31101.00 Update 4. I also tested it with Visual Studio Community 2013. As far as I know VS Community is pretty much the same as VS Professional.

**Comment by Luigius** [comment]
Hi,
I get the same error also using VS 2013 Ultimate.

Please advise.
BTW the GITHUB page is not found.

Thanks
Luigi
[image: Inline image 1]

**Comment by ladimolnar** [comment]
I think I know what is going on but the fix may not be that simple. Unintentionally I created my PCL for a profile that includes Win Phone 8.1. Changing the PCL profile turns out to be tricky. Turns out that I am using things like Task.WhenAll that are not available in PCL profiles that would be OK for you. I thought that this would be as simple as changing the PCL profile and using the Bcl.Async package to compensate but it seems that Task.WhenAll is not available there either. 

I am going to find a solution but may not be today. Today I am going to concentrate on releasing a binary that no longer takes SQL Server SMO dependencies - that should unblock you. Then I am going to look at tweaking the sources so that you can compile them without installing some Win Phone SDK. .

**Comment by ladimolnar** [comment]
Hello Luigi, 

I released a new version (V 1.1) that has the tool without the dependencies on the DLLs that caused you problems. 

If you are not able to reach my GitHub page that is because GitHub suspects me as being a robot. I assume that is due to the links we posted on this thread but it could be other reason - who knows. I contacted support and I hope they will remedy this soon.

**Comment by ladimolnar** [comment]
Hello Luigi,

I changed the PCLs to a different profile that I hope will work fine for you. Sync your sources to the latest changes and try to build again. I would be curious if you can do so with VS 2012. 

Let me know,
Ladi

**Comment by ladimolnar** [comment]
Hello Luigi, 

GitHub support reinstated my account. You should now have access to my page.

**Comment by Luigius** [comment]
Hi Ladi,

the exe works fine, but the source code still give me the same error related to the last 2 projects.
Here the pic of the screen. As soon as the code works I will try also on a machine where I have 2012 and I can also try 2010.

Thanks a lot, I will contact you on your personal email.
Luigi

**Comment by Luigius** [comment]
Sorry I forgot the pic
![untitled3](https://cloud.githubusercontent.com/assets/4317527/7760700/fc1b4274-ffd2-11e4-8ab2-7f6f3077f79f.png)

**Comment by ladimolnar** [comment]
Hello Luigi,

I am assuming that you did sync to my latest changes.I never run VS on WIN 2012 R2 Server OS and I start suspecting that may have something to do with it. Do you have a dev machine with Windows 8 or Windows 8.1? 

The PCLs that fail to load on your machine have dependencies on .NET Framework 4.5 and on Windows 8. Determine what version of the .NET Framework you have on your machine and if you have the Windows 8 SDK installed. Go to the link provided in the build error message and take a look at that list. I expect that you do have .NET Framework 4.5 on your machine. But maybe the issue is around the Windows 8 SDK? 

BTW, I just installed a clean VM with Windows 8.1 Pro, VS 2013 Community edition and StyleCop 4.7, The projects loaded fine. The build succeeded although I had to do a few clean builds to get there due to a NuGet / VS quirk.

**Comment by Luigius** [comment]
Hi Ladi,
I will try on a 8.1 VS 2013.

for the Server 2012 I will let you know if installing Win 8 SDK make any
difference.

Thanks again
Luigi

**Comment by Luigius** [comment]
Hi Ladi,

I'm checked several times, but I think the bitcoin address is not extracted in the process and added to the DB is that correct?

Thanks
Luigi

**Comment by ladimolnar** [comment]
At this point I do not extract the Bitcoin address in an easy to read form. You may be able to extract what you need yourself from column TransactionOutput.OutputScript but in order to do that you need to know how to decode Bitcoin scripts. I will try to add that in the future if I have time. However, if you think of decoding that on your own beware of muti-signature transactions. In that case you cannot simply say what the Bitcoin address is. It can be a combination of multiple addresses. That is the reason I did not implemented such feature yet.

**Comment by ladimolnar** [comment]
Luigi,

I made further changes that hopefully will fix the issues that you had building on WIN 2012 R2 Server OS. You should not need to install any SDK. I did not have that configuration available to test the build though. 

I also added build prerequisite info on the home page of the project and on the home page of the wiki. 

With this, I consider all the issue you raised resolved. Feel free to reopen if you think that is not the case.
