### ISSUE TITLE
files to copy

### ISSUE THREAD

**Issue by ozeiuyo** [ladimolnar/BitcoinDatabaseGenerator#11]
in which directory of bitcoin core i have to copy the files ;
which commands i have to use

**Comment by ladimolnar** [comment]
Run "BitcoinDatabaseGenerator /?" and read carefully the output. Or visit: https://github.com/ladimolnar/BitcoinDatabaseGenerator/wiki/Usage

**Comment by ozeiuyo** [comment]
hi, I don't find bitcoindatabasegenerator.exe in the file i've download.

2017-04-24 4:48 GMT+02:00 Ladislau Molnar <notifications@github.com>:

**Comment by ladimolnar** [comment]
Which file you downloaded exactly. Are you referring to BitcoinDatabaseGenerator_1_8.zip from https://github.com/ladimolnar/BitcoinDatabaseGenerator/releases? That is the file that contains the last release and inside the folder BitcoinDatabaseGenerator_1_8 it does contain the file bitcoindatabasegenerator.exe.

Sometimes antiviruses may decide to delete files when extracted from ZIP because of a "low reputation score" - that means that although they do not detect a specific threat there are not enough people that use these files hence the antivirus does not trust it. If that happens you will have to manually instruct your antivirus to restore those files.

**Comment by ozeiuyo** [comment]
i have find the file thank's

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-04-25 9:06 GMT+02:00 Ladislau Molnar <notifications@github.com>:
